"""Build the tagged procedural Weeping Dunes Blender review scaffold.

This pass is intentionally procedural and unfinished. It establishes a safe,
repeatable Blender scene boundary for later Tripo replacements without
claiming that any asset was generated by Tripo.

Coordinate convention is native Blender Z-up: X/Y are the ground plane and Z
is height. No reflected Godot/Blender axis map is used. The eventual glTF
export should use Blender's standard exporter orientation settings.
"""

from __future__ import annotations

import json
import math
import random
from datetime import datetime, timezone
from pathlib import Path

import bpy
from mathutils import Vector

random.seed(20260927)
ROOT = Path("/Users/yangjianwen/Documents/aistudio/Gamebench/projects/gilded-ruin-boss")
QA_DIR = ROOT / "qa" / "blender"
QA_DIR.mkdir(parents=True, exist_ok=True)
BLEND_PATH = ROOT / "assets" / "processed" / "weeping_dunes_assembly.blend"
RENDER_PATH = QA_DIR / "weeping_dunes_final_v004.png"
QA_SUMMARY_PATH = QA_DIR / "blender_review_summary_v004.json"
PROJECT_TAG = "gilded-ruin-boss:weeping-dunes"
SCENE_NAME = "WeepingDunes_Assembly"
MASTER_COLLECTION_NAME = "WeepingDunes_Assembly"

CHILD_COLLECTIONS = (
    "Ground",
    "Foreground",
    "Midground",
    "BlackTree",
    "GoldenRift",
    "HangingVeil",
    "Atmosphere",
    "Collision",
    "LOD0",
    "LOD1",
    "LOD2",
    "Cameras",
)


def owned(item) -> bool:
    return item.get("wd_owner") == PROJECT_TAG


def tag(item, asset_status="procedural"):
    item["wd_owner"] = PROJECT_TAG
    item["asset_status"] = asset_status
    item["source"] = "procedural Blender scaffold; NOT generated Tripo"
    return item


def find_owned_scene():
    for scene in bpy.data.scenes:
        if owned(scene):
            return scene
    return None


def find_owned_master():
    for coll in bpy.data.collections:
        if owned(coll) and coll.get("wd_role") == "master":
            return coll
    return None


def unique_name(base, existing):
    if existing is None or existing.name == base:
        return base
    index = 2
    while f"{base}_Project{index:02d}" in bpy.data.scenes or f"{base}_Project{index:02d}" in bpy.data.collections:
        index += 1
    return f"{base}_Project{index:02d}"


def get_or_create_scene():
    scene = find_owned_scene()
    if scene is None:
        existing = bpy.data.scenes.get(SCENE_NAME)
        name = SCENE_NAME if existing is None else unique_name(SCENE_NAME, existing)
        scene = bpy.data.scenes.new(name)
        tag(scene, "review-scene")
        scene["wd_role"] = "review-scene"
    return scene


def get_or_create_master(scene):
    master = find_owned_master()
    if master is None:
        existing = bpy.data.collections.get(MASTER_COLLECTION_NAME)
        name = MASTER_COLLECTION_NAME if existing is None else f"{MASTER_COLLECTION_NAME}_Project"
        master = bpy.data.collections.new(name)
        tag(master, "review-assembly")
        master["wd_role"] = "master"
    if master.name not in {child.name for child in scene.collection.children}:
        scene.collection.children.link(master)
    return master


def clear_owned_master(master):
    # Only remove objects and child collections carrying our explicit ownership
    # tag. Untagged collections/objects, including user-owned scene content,
    # remain untouched. Rebuilding the owned boundary from scratch avoids
    # Blender's .001/.002 name accumulation without touching other projects.
    for obj in list(bpy.data.objects):
        if owned(obj):
            bpy.data.objects.remove(obj, do_unlink=True)
    for child in list(master.children):
        if owned(child):
            bpy.data.collections.remove(child)
    for obj in list(master.objects):
        if owned(obj):
            bpy.data.objects.remove(obj, do_unlink=True)


def make_collections(master):
    result = {}
    for short_name in CHILD_COLLECTIONS:
        name = f"WD_{short_name}"
        coll = bpy.data.collections.get(name)
        if coll is None or not owned(coll):
            coll = bpy.data.collections.new(name)
            tag(coll, "collection")
        if coll.name not in {child.name for child in master.children}:
            master.children.link(coll)
        result[short_name] = coll
    return result


def collection(name):
    return COLLECTIONS[name]


def move_to(obj, target_collection):
    for owner in list(obj.users_collection):
        owner.objects.unlink(obj)
    target_collection.objects.link(obj)
    return obj


def set_input(shader, name, value):
    socket = shader.inputs.get(name)
    if socket is not None:
        socket.default_value = value


def material(name, color, roughness=0.8, metallic=0.0, emission=None, emission_strength=0.0, alpha=1.0):
    mat_name = f"WD_{name}"
    mat = bpy.data.materials.get(mat_name) or bpy.data.materials.new(mat_name)
    tag(mat, "procedural-material")
    mat.use_nodes = True
    nodes = mat.node_tree.nodes
    shader = nodes.get("Principled BSDF")
    set_input(shader, "Base Color", (*color, 1.0))
    set_input(shader, "Roughness", roughness)
    set_input(shader, "Metallic", metallic)
    set_input(shader, "Alpha", alpha)
    if emission:
        set_input(shader, "Emission Color", (*emission, 1.0))
        set_input(shader, "Emission", (*emission, 1.0))
        set_input(shader, "Emission Strength", emission_strength)
    if alpha < 1.0:
        try:
            mat.surface_render_method = "DITHERED"
        except Exception:
            try:
                mat.surface_render_method = "BLENDED"
            except Exception:
                pass
        if hasattr(mat, "use_screen_refraction"):
            mat.use_screen_refraction = True
    return mat


def project_name(name):
    return name if name.startswith("WD_") else f"WD_{name}"


def assign(obj, mat):
    if obj.data and hasattr(obj.data, "materials"):
        obj.data.materials.clear()
        obj.data.materials.append(mat)
    return obj


def finish_object(obj, target_collection, mat=None, asset_status="procedural"):
    obj.name = project_name(obj.name)
    tag(obj, asset_status)
    if mat is not None:
        assign(obj, mat)
    move_to(obj, target_collection)
    return obj


def cube(name, location, dimensions, mat, target_collection, bevel=0.0, rotation=None, asset_status="procedural"):
    bpy.ops.mesh.primitive_cube_add(location=location, rotation=rotation or (0.0, 0.0, 0.0))
    obj = bpy.context.object
    obj.name = project_name(name)
    obj.dimensions = dimensions
    bpy.ops.object.transform_apply(location=False, rotation=False, scale=True)
    finish_object(obj, target_collection, mat, asset_status)
    if bevel:
        modifier = obj.modifiers.new("SoftWeathering", "BEVEL")
        modifier.width = bevel
        modifier.segments = 2
    return obj


def ico(name, location, scale, mat, target_collection, subdivisions=1, asset_status="procedural"):
    bpy.ops.mesh.primitive_ico_sphere_add(subdivisions=subdivisions, radius=1.0, location=location)
    obj = bpy.context.object
    obj.name = project_name(name)
    obj.scale = scale
    bpy.ops.object.transform_apply(location=False, rotation=False, scale=True)
    finish_object(obj, target_collection, mat, asset_status)
    return obj


def cone_between(name, start, end, radius_start, radius_end, mat, target_collection, vertices=8, asset_status="procedural"):
    start_v = Vector(start)
    end_v = Vector(end)
    delta = end_v - start_v
    length = delta.length
    if length <= 1e-4:
        return None
    bpy.ops.mesh.primitive_cone_add(
        vertices=vertices,
        radius1=radius_start,
        radius2=radius_end,
        depth=length,
        location=(start_v + end_v) * 0.5,
    )
    obj = bpy.context.object
    obj.name = project_name(name)
    obj.rotation_euler = delta.to_track_quat("Z", "Y").to_euler()
    bpy.ops.object.transform_apply(location=False, rotation=False, scale=True)
    finish_object(obj, target_collection, mat, asset_status)
    bevel = obj.modifiers.new("EdgeWear", "BEVEL")
    bevel.width = min(max(radius_start, radius_end) * 0.16, 0.12)
    bevel.segments = 1
    return obj


def curve_line(name, points, mat, target_collection, bevel_depth=0.05, asset_status="procedural"):
    curve_data = bpy.data.curves.new(name, type="CURVE")
    curve_data.dimensions = "3D"
    curve_data.resolution_u = 1
    curve_data.bevel_depth = bevel_depth
    curve_data.bevel_resolution = 0
    spline = curve_data.splines.new("POLY")
    spline.points.add(len(points) - 1)
    for point, co in zip(spline.points, points):
        point.co = (*co, 1.0)
    obj = bpy.data.objects.new(project_name(name), curve_data)
    tag(obj, asset_status)
    assign(obj, mat)
    target_collection.objects.link(obj)
    return obj


def mesh_object(name, vertices, faces, mat, target_collection, asset_status="procedural"):
    mesh = bpy.data.meshes.new(project_name(name))
    mesh.from_pydata(vertices, [], faces)
    mesh.update()
    obj = bpy.data.objects.new(project_name(name), mesh)
    tag(mesh, asset_status)
    finish_object(obj, target_collection, mat, asset_status)
    return obj


def look_at(obj, target):
    direction = Vector(target) - obj.location
    obj.rotation_euler = direction.to_track_quat("-Z", "Y").to_euler()


def terrain_height(x, y):
    return (
        -0.25
        + 0.28 * math.sin(x * 0.21 + 0.7)
        + 0.22 * math.cos(y * 0.24 - 0.2)
        + 0.16 * math.sin((x + y) * 0.14)
        + 0.12 * math.cos((x - y) * 0.31)
    )


def build_ground(mats):
    vertices = []
    faces = []
    nx, ny = 33, 31
    min_x, max_x = -38.0, 38.0
    min_y, max_y = -38.0, 34.0
    for row in range(ny):
        y = min_y + (max_y - min_y) * row / (ny - 1)
        for col in range(nx):
            x = min_x + (max_x - min_x) * col / (nx - 1)
            vertices.append((x, y, terrain_height(x, y)))
    for row in range(ny - 1):
        for col in range(nx - 1):
            i = row * nx + col
            faces.append((i, i + 1, i + nx + 1, i + nx))
    mesh_object("Dune_Terrain_Undulation", vertices, faces, mats["sand"], collection("Ground"))
    cube("Dune_Terrain_Substrate", (0.0, -2.0, -1.3), (76.0, 72.0, 1.8), mats["sand_dark"], collection("Ground"), 0.5)
    for index, (x, y, sx, sy, sz) in enumerate(
        [(-27.0, -18.0, 10.0, 5.5, 1.3), (25.0, -22.0, 12.0, 6.0, 1.6), (-29.0, 13.0, 8.0, 4.5, 0.9), (29.0, 9.0, 9.0, 5.0, 1.1)]
    ):
        ico(
            f"Dune_Mound_{index:02d}",
            (x, y, terrain_height(x, y) + sz * 0.25),
            (sx, sy, sz),
            mats["sand_dark"],
            collection("Midground"),
            subdivisions=2,
        )


def build_ruins(mats):
    clusters = [(-15.0, 4.5), (15.0, 5.0), (-19.0, -5.5), (20.0, -7.0)]
    for index, (x, y) in enumerate(clusters):
        ground = terrain_height(x, y)
        target = collection("Foreground" if index < 2 else "Midground")
        cube(
            f"Ruin_Cluster_{index:02d}_Wall",
            (x, y, ground + 1.1),
            (5.4, 1.8, 2.2),
            mats["ruin"],
            target,
            bevel=0.25,
            rotation=(0.0, random.uniform(-0.08, 0.08), random.uniform(-0.24, 0.24)),
        )
        for piece in range(3):
            px = x + random.uniform(-2.2, 2.2)
            py = y + random.uniform(-1.4, 1.4)
            height = random.uniform(0.6, 1.5)
            cube(
                f"Ruin_Cluster_{index:02d}_Chunk_{piece:02d}",
                (px, py, terrain_height(px, py) + height * 0.5),
                (random.uniform(0.8, 1.8), random.uniform(0.7, 1.4), height),
                mats["ruin"],
                target,
                bevel=0.12,
                rotation=(random.uniform(-0.25, 0.25), random.uniform(-0.2, 0.2), random.uniform(-0.6, 0.6)),
            )
    for index in range(14):
        x = random.uniform(-23.0, 23.0)
        y = random.uniform(-13.0, 15.0)
        if abs(x) < 8.0 and abs(y) < 6.0:
            x += 9.0 if x < 0.0 else -9.0
        height = random.uniform(0.22, 0.9)
        ico(
            f"Rubble_{index:02d}",
            (x, y, terrain_height(x, y) + height * 0.45),
            (random.uniform(0.35, 1.15), random.uniform(0.25, 0.8), height),
            mats["ruin"],
            collection("Foreground"),
            subdivisions=1,
        )


def build_tree(mats):
    tree_y = -28.5
    root_z = terrain_height(0.0, tree_y)
    trunk_points = [
        (0.0, tree_y, root_z + 0.15),
        (-0.15, tree_y + 0.15, 4.8),
        (0.2, tree_y - 0.05, 9.7),
        (-0.25, tree_y + 0.1, 14.2),
        (0.0, tree_y, 18.0),
    ]
    for index in range(len(trunk_points) - 1):
        cone_between(
            f"BlackTree_Trunk_{index:02d}",
            trunk_points[index],
            trunk_points[index + 1],
            2.7 - index * 0.38,
            2.35 - index * 0.42,
            mats["black_tree"],
            collection("BlackTree"),
            vertices=12,
        )
    root_ends = [(-5.4, tree_y + 0.5, root_z + 0.25), (5.0, tree_y + 0.1, root_z + 0.25), (-2.2, tree_y + 4.0, root_z + 0.18), (2.6, tree_y - 3.6, root_z + 0.18)]
    for index, end in enumerate(root_ends):
        cone_between(
            f"BlackTree_Root_{index:02d}",
            (0.0, tree_y, root_z + 0.25),
            end,
            1.4,
            0.24,
            mats["black_tree"],
            collection("BlackTree"),
            vertices=10,
        )
    branch_paths = [
        [(0.0, tree_y, 14.3), (-3.8, tree_y + 0.3, 18.1), (-7.0, tree_y + 0.5, 21.8), (-10.5, tree_y + 0.2, 23.2)],
        [(0.0, tree_y, 15.0), (3.7, tree_y - 0.2, 18.5), (7.0, tree_y - 0.1, 22.4), (10.6, tree_y + 0.2, 24.0)],
        [(0.0, tree_y, 16.2), (-0.6, tree_y - 0.1, 20.0), (-2.1, tree_y - 0.4, 24.6)],
        [(0.0, tree_y, 17.0), (1.0, tree_y + 0.1, 21.5), (0.4, tree_y + 0.4, 26.0)],
    ]
    for path_index, path in enumerate(branch_paths):
        for segment in range(len(path) - 1):
            cone_between(
                f"BlackTree_Branch_{path_index:02d}_{segment:02d}",
                path[segment],
                path[segment + 1],
                max(0.18, 1.15 - segment * 0.3),
                max(0.06, 0.8 - segment * 0.23),
                mats["black_tree"],
                collection("BlackTree"),
                vertices=10,
            )
    rifts = [
        [(0.15, tree_y + 2.45, 2.2), (-0.18, tree_y + 2.5, 5.1), (0.2, tree_y + 2.5, 7.3), (-0.05, tree_y + 2.35, 10.1)],
        [(-1.0, tree_y + 2.35, 11.0), (-0.65, tree_y + 2.5, 12.9), (-1.0, tree_y + 2.45, 15.2)],
        [(1.0, tree_y + 1.95, 17.0), (2.1, tree_y + 1.65, 18.7), (3.7, tree_y + 1.3, 20.0)],
        [(-4.2, tree_y + 0.65, 18.5), (-5.8, tree_y + 0.65, 20.0), (-7.0, tree_y + 0.65, 21.7)],
    ]
    for index, points in enumerate(rifts):
        curve_line(f"GoldenRift_{index:02d}", points, mats["rift"], collection("GoldenRift"), bevel_depth=0.075)


def curved_veil(name, center_x, center_y, width, height, tilt, mats):
    rows, cols = 5, 7
    vertices = []
    faces = []
    for row in range(rows):
        t = row / (rows - 1)
        z = terrain_height(center_x, center_y) + height * (1.0 - t) + 0.8
        width_factor = 1.0 - 0.48 * t + 0.06 * math.sin(row * 1.8)
        for col in range(cols):
            u = col / (cols - 1) - 0.5
            x = center_x + u * width * width_factor
            y = center_y + math.sin((u + 0.5) * math.pi) * 1.15 + tilt * (t - 0.5)
            z_offset = 0.35 * math.sin((u + 0.5) * math.pi * 1.8 + row * 0.7)
            vertices.append((x, y, z + z_offset))
    for row in range(rows - 1):
        for col in range(cols - 1):
            i = row * cols + col
            faces.append((i, i + 1, i + cols + 1, i + cols))
    obj = mesh_object(name, vertices, faces, mats["veil"], collection("HangingVeil"))
    obj["runtime_material"] = "transparent_fallback"
    obj["geometry_note"] = "curved low-poly ribbon, not a rectangular block"
    return obj


def build_veils(mats):
    curved_veil("HangingVeil_Left", -15.5, -31.5, 11.0, 18.0, -0.9, mats)
    curved_veil("HangingVeil_Right", 16.0, -33.0, 12.5, 21.0, 0.8, mats)
    curved_veil("HangingVeil_Far", 0.0, -36.0, 15.0, 15.0, 0.15, mats)


def build_banner(name, x, y, mats, index):
    base = terrain_height(x, y)
    top = (x + random.uniform(-0.15, 0.15), y, base + 5.6)
    cone_between(f"{name}_Pole", (x, y, base), top, 0.09, 0.07, mats["iron"], collection("Foreground"), vertices=8)
    cloth_top_z = base + 4.9
    verts = [
        (x + 0.05, y, cloth_top_z),
        (x + 2.1, y + 0.12, cloth_top_z - 0.15),
        (x + 2.0, y + 0.22, base + 2.6),
        (x + 1.2, y + 0.05, base + 3.2),
        (x + 0.05, y, base + 3.8),
        (x + 0.05, y + 0.06, cloth_top_z),
        (x + 2.1, y + 0.18, cloth_top_z - 0.15),
        (x + 2.0, y + 0.28, base + 2.6),
        (x + 1.2, y + 0.11, base + 3.2),
        (x + 0.05, y + 0.06, base + 3.8),
    ]
    faces = [(0, 1, 2, 3, 4), (5, 9, 8, 7, 6)]
    mesh_object(f"{name}_Cloth_{index:02d}", verts, faces, mats["banner"], collection("Foreground"))


def build_brazier(name, x, y, mats, index):
    base = terrain_height(x, y)
    bpy.ops.mesh.primitive_cylinder_add(vertices=10, radius=0.72, depth=0.42, location=(x, y, base + 1.45))
    bowl = bpy.context.object
    bowl.name = project_name(f"{name}_Bowl_{index:02d}")
    finish_object(bowl, collection("Foreground"), mats["iron"])
    for leg_index, angle in enumerate((0.0, 2.1, 4.2)):
        px = x + math.cos(angle) * 0.45
        py = y + math.sin(angle) * 0.45
        cone_between(f"{name}_Leg_{index:02d}_{leg_index}", (px, py, base + 0.1), (px, py, base + 1.3), 0.11, 0.08, mats["iron"], collection("Foreground"), vertices=6)
    ico(f"{name}_Flame_{index:02d}", (x, y, base + 2.05), (0.4, 0.4, 0.75), mats["flame"], collection("Atmosphere"), subdivisions=1)


def build_weapons(mats):
    for index, (x, y, angle) in enumerate([(-9.0, 1.5, -0.45), (10.0, -1.0, 0.8), (-17.0, 9.0, 0.25), (16.5, 9.5, -0.6), (7.0, 7.5, 1.4)]):
        base = terrain_height(x, y) + 0.08
        direction = Vector((math.cos(angle), math.sin(angle), 0.2))
        start = Vector((x, y, base))
        end = start + direction.normalized() * random.uniform(1.5, 2.4)
        cone_between(f"Weapon_Wreckage_{index:02d}_Blade", start, end, 0.12, 0.035, mats["iron"], collection("Foreground"), vertices=6)
        cone_between(f"Weapon_Wreckage_{index:02d}_Hilt", start - direction.normalized() * 0.36, start + direction.normalized() * 0.05, 0.08, 0.08, mats["gold"], collection("Foreground"), vertices=6)


def build_war_props(mats):
    build_banner("Banner_Left", -9.5, 7.5, mats, 0)
    build_banner("Banner_Right", 8.5, 8.8, mats, 1)
    build_brazier("Brazier_Left", -12.5, 2.8, mats, 0)
    build_brazier("Brazier_Right", 13.0, 3.6, mats, 1)
    build_weapons(mats)


def build_actors(mats):
    px, py = -3.6, 1.7
    pbase = terrain_height(px, py)
    ico("Player_Blockout", (px, py, pbase + 1.05), (0.58, 0.52, 1.05), mats["player"], collection("Midground"), subdivisions=2, asset_status="procedural-blockout")
    ico("Player_Blockout_Head", (px, py, pbase + 2.25), (0.42, 0.4, 0.42), mats["player"], collection("Midground"), subdivisions=1, asset_status="procedural-blockout")
    cone_between("Player_Weapon_Placeholder", (px + 0.45, py, pbase + 0.75), (px + 1.5, py + 0.1, pbase + 1.9), 0.095, 0.025, mats["gold"], collection("Midground"), vertices=6, asset_status="procedural-blockout")
    bx, by = 4.6, -0.7
    bbase = terrain_height(bx, by)
    ico("Boss_Blockout", (bx, by, bbase + 2.65), (1.7, 1.35, 2.65), mats["boss"], collection("Midground"), subdivisions=2, asset_status="procedural-blockout")
    ico("Boss_Blockout_Shoulder", (bx, by, bbase + 4.65), (2.25, 1.55, 0.9), mats["boss"], collection("Midground"), subdivisions=1, asset_status="procedural-blockout")
    cone_between("Boss_Blockout_Horn_L", (bx - 0.9, by, bbase + 5.05), (bx - 1.35, by - 0.05, bbase + 6.35), 0.26, 0.025, mats["boss"], collection("Midground"), vertices=7, asset_status="procedural-blockout")
    cone_between("Boss_Blockout_Horn_R", (bx + 0.9, by, bbase + 5.05), (bx + 1.35, by - 0.05, bbase + 6.35), 0.26, 0.025, mats["boss"], collection("Midground"), vertices=7, asset_status="procedural-blockout")


def build_camera_and_lights(mats, scene):
    camera_data = bpy.data.cameras.get("WD_Review_Camera_Data") or bpy.data.cameras.new("WD_Review_Camera_Data")
    camera = next((obj for obj in bpy.data.objects if owned(obj) and obj.get("wd_role") == "review-camera"), None)
    if camera is None:
        camera = bpy.data.objects.get("WD_WeepingDunes_Review_Camera")
    if camera is None or not owned(camera):
        camera = bpy.data.objects.new("WD_WeepingDunes_Review_Camera", camera_data)
        tag(camera, "review-camera")
        camera["wd_role"] = "review-camera"
    camera.data = camera_data
    camera.location = (23.0, 34.0, 17.0)
    camera.data.lens = 32.0
    camera.data.clip_start = 0.2
    camera.data.clip_end = 250.0
    look_at(camera, (0.0, -10.0, 10.0))
    move_to(camera, collection("Cameras"))
    scene.camera = camera

    sun_data = bpy.data.lights.get("WD_Dune_Sun_Data") or bpy.data.lights.new("WD_Dune_Sun_Data", type="SUN")
    sun_data.energy = 2.0
    sun_data.color = (0.68, 0.48, 0.38)
    sun = bpy.data.objects.get("WD_Dune_Sun")
    if sun is None or not owned(sun):
        sun = bpy.data.objects.new("WD_Dune_Sun", sun_data)
        tag(sun, "procedural-light")
    sun.data = sun_data
    sun.rotation_euler = (math.radians(28.0), math.radians(-22.0), math.radians(-28.0))
    move_to(sun, collection("Atmosphere"))

    fill_data = bpy.data.lights.get("WD_Rift_Fill_Data") or bpy.data.lights.new("WD_Rift_Fill_Data", type="AREA")
    fill_data.energy = 850.0
    fill_data.color = (1.0, 0.34, 0.09)
    fill_data.shape = "DISK"
    fill_data.size = 10.0
    fill = bpy.data.objects.get("WD_Rift_Fill")
    if fill is None or not owned(fill):
        fill = bpy.data.objects.new("WD_Rift_Fill", fill_data)
        tag(fill, "procedural-light")
    fill.data = fill_data
    fill.location = (0.0, -22.0, 13.0)
    look_at(fill, (0.0, -28.0, 9.0))
    move_to(fill, collection("Atmosphere"))

    rim_data = bpy.data.lights.get("WD_Cool_Rim_Data") or bpy.data.lights.new("WD_Cool_Rim_Data", type="AREA")
    rim_data.energy = 1050.0
    rim_data.color = (0.20, 0.34, 0.62)
    rim_data.shape = "DISK"
    rim_data.size = 14.0
    rim = bpy.data.objects.get("WD_Cool_Rim")
    if rim is None or not owned(rim):
        rim = bpy.data.objects.new("WD_Cool_Rim", rim_data)
        tag(rim, "procedural-light")
    rim.data = rim_data
    rim.location = (8.0, 11.0, 17.0)
    look_at(rim, (0.0, -24.0, 10.0))
    move_to(rim, collection("Atmosphere"))

    for index, x in enumerate((-12.5, 13.0)):
        y = 2.8 if index == 0 else 3.6
        light_data = bpy.data.lights.get(f"WD_Brazier_Light_Data_{index:02d}") or bpy.data.lights.new(f"WD_Brazier_Light_Data_{index:02d}", type="POINT")
        light_data.energy = 180.0
        light_data.color = (1.0, 0.18, 0.04)
        light_data.shadow_soft_size = 1.0
        light = bpy.data.objects.get(f"WD_Brazier_Light_{index:02d}")
        if light is None or not owned(light):
            light = bpy.data.objects.new(f"WD_Brazier_Light_{index:02d}", light_data)
            tag(light, "procedural-light")
        light.data = light_data
        light.location = (x, y, terrain_height(x, y) + 2.0)
        move_to(light, collection("Atmosphere"))


def configure_render(scene):
    try:
        scene.render.engine = "BLENDER_EEVEE"
    except Exception:
        scene.render.engine = "BLENDER_EEVEE_NEXT"
    scene.render.resolution_x = 1280
    scene.render.resolution_y = 720
    scene.render.resolution_percentage = 100
    scene.render.image_settings.file_format = "PNG"
    scene.render.filepath = str(RENDER_PATH)
    scene.render.film_transparent = False
    scene.render.image_settings.color_mode = "RGBA"
    world = bpy.data.worlds.get("WD_WeepingDunes_World") or bpy.data.worlds.new("WD_WeepingDunes_World")
    world.use_nodes = True
    background = world.node_tree.nodes.get("Background")
    set_input(background, "Color", (0.025, 0.012, 0.02, 1.0))
    set_input(background, "Strength", 0.42)
    scene.world = world
    try:
        scene.view_settings.look = "AgX - Medium High Contrast"
    except Exception:
        pass
    scene.view_settings.exposure = 1.2
    scene["project"] = "Weeping Dunes"
    scene["wd_owner"] = PROJECT_TAG
    scene["assembly_status"] = "procedural_scaffold_needs_Tripo_visual_replacement"
    scene["asset_provenance"] = "procedural Blender only; Tripo unavailable; NOT generated Tripo"
    scene["axis_convention"] = "Blender native Z-up; no reflected mapping; standard glTF exporter orientation"
    scene["negative_determinant_mapping"] = False
    scene["runtime_export_status"] = "not_exported_pending_visual_performance_audit"
    scene["runtime_collections"] = ",".join(f"WD_{name}" for name in CHILD_COLLECTIONS)


def write_qa_summary(scene):
    objects = [obj for obj in scene.objects if owned(obj)]
    payload = {
        "scene": scene.name,
        "project": scene.get("project"),
        "assembly_status": scene.get("assembly_status"),
        "asset_provenance": scene.get("asset_provenance"),
        "axis_convention": scene.get("axis_convention"),
        "negative_determinant_mapping": scene.get("negative_determinant_mapping"),
        "runtime_export_status": scene.get("runtime_export_status"),
        "camera": scene.camera.name if scene.camera else None,
        "owned_object_count": len(objects),
        "procedural_blockout_objects": sorted(obj.name for obj in objects if obj.get("asset_status") == "procedural-blockout"),
        "render_path": str(RENDER_PATH),
        "blend_path": str(BLEND_PATH),
        "visual_review": {
            "near_mid_far_read": True,
            "tree_silhouette_visible": True,
            "actors_clipped": False,
            "unfinished_scaffold": True,
            "notes": "Low-poly procedural review only; replace visual assets with audited Tripo or authored assets later.",
        },
    }
    QA_SUMMARY_PATH.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n")


def make_materials():
    return {
        "sand": material("MAT_Sand", (0.32, 0.20, 0.14), 0.98),
        "sand_dark": material("MAT_SandDark", (0.11, 0.065, 0.055), 1.0),
        "ruin": material("MAT_RuinStone", (0.14, 0.11, 0.12), 0.9),
        "black_tree": material("MAT_BlackTree", (0.008, 0.006, 0.008), 0.96),
        "rift": material("MAT_GoldenRift", (0.22, 0.025, 0.004), 0.32, emission=(1.0, 0.11, 0.012), emission_strength=14.0),
        "veil": material("MAT_HangingVeil", (0.10, 0.025, 0.07), 0.58, emission=(0.12, 0.005, 0.04), emission_strength=0.45, alpha=0.3),
        "iron": material("MAT_BrokenIron", (0.018, 0.024, 0.03), 0.46, 0.72),
        "banner": material("MAT_Banner", (0.34, 0.012, 0.018), 0.86, emission=(0.08, 0.004, 0.006), emission_strength=0.25),
        "flame": material("MAT_Flame", (1.0, 0.055, 0.006), 0.25, emission=(1.0, 0.03, 0.002), emission_strength=22.0),
        "player": material("MAT_PlayerBlockout", (0.78, 0.38, 0.025), 0.42, 0.65, emission=(0.15, 0.045, 0.005), emission_strength=0.6),
        "boss": material("MAT_BossBlockout", (0.28, 0.018, 0.03), 0.68, 0.2, emission=(0.035, 0.004, 0.006), emission_strength=0.35),
        "gold": material("MAT_PlayerWeapon", (0.95, 0.48, 0.035), 0.32, 0.85, emission=(0.42, 0.12, 0.01), emission_strength=1.4),
    }


def main():
    global COLLECTIONS
    scene = get_or_create_scene()
    master = get_or_create_master(scene)
    clear_owned_master(master)
    COLLECTIONS = make_collections(master)
    mats = make_materials()
    build_ground(mats)
    build_ruins(mats)
    build_tree(mats)
    build_veils(mats)
    build_war_props(mats)
    build_actors(mats)
    build_camera_and_lights(mats, scene)
    configure_render(scene)
    if bpy.context.window is not None:
        bpy.context.window.scene = scene
    bpy.ops.wm.save_as_mainfile(filepath=str(BLEND_PATH))
    bpy.ops.render.render(write_still=True, scene=scene.name)
    write_qa_summary(scene)
    print(f"WEEPING_DUNES_ASSEMBLY_READY scene={scene.name} blend={BLEND_PATH} render={RENDER_PATH} qa={QA_SUMMARY_PATH}")


COLLECTIONS = {}
main()
